php
<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'create deficiencies',
            'view deficiencies',
            'edit deficiencies',
            'delete deficiencies',
            'create projects',
            'view projects',
            'edit projects',
            'delete projects',
            'create vendors',
            'view vendors',
            'edit vendors',
            'delete vendors',
            'create users',
            'view users',
            'edit users',
            'delete users',
            'create submittals',
            'view submittals',
            'edit submittals',
            'delete submittals',
            'create roles',
            'view roles',
            'edit roles',
            'delete roles',
            'create rfis',
            'view rfis',
            'edit rfis',
            'delete rfis',
            'create qualified bidders',
            'view qualified bidders',
            'edit qualified bidders',
            'delete qualified bidders',
            'create purchase orders',
            'view purchase orders',
            'edit purchase orders',
            'delete purchase orders',
            'create punch lists',
            'view punch lists',
            'edit punch lists',
            'delete punch lists',
            'create project infos',
            'view project infos',
            'edit project infos',
            'delete project infos',
            'create observations',
            'view observations',
            'edit observations',
            'delete observations',
            'create manpower logs',
            'view manpower logs',
            'edit manpower logs',
            'delete manpower logs',
            'create daily logs',
            'view daily logs',
            'edit daily logs',
            'delete daily logs',
            'create cost codes',
            'view cost codes',
            'edit cost codes',
            'delete cost codes',
            'create contracts',
            'view contracts',
            'edit contracts',
            'delete contracts',
            'create companies',
            'view companies',
            'edit companies',
            'delete companies',
            'create comments',
            'view comments',
            'edit comments',
            'delete comments',
            'create change orders',
            'view change orders',
            'edit change orders',
            'delete change orders',
            'create bid packages',
            'view bid packages',
            'edit bid packages',
            'delete bid packages',
            'create bid manuals',
            'view bid manuals',
            'edit bid manuals',
            'delete bid manuals',
            'create bims',
            'view bims',
            'edit bims',
            'delete bims',
            'create closeouts',
            'view closeouts',
            'edit closeouts',
            'delete closeouts',
            'create contractss',
            'view contractss',
            'edit contractss',
            'delete contractss',
            'create costs',
            'view costs',
            'edit costs',
            'delete costs',
            'create engineerings',
            'view engineerings',
            'edit engineerings',
            'delete engineerings',
            'create fields',
            'view fields',
            'edit fields',
            'delete fields',
            'create preconstructions',
            'view preconstructions',
            'edit preconstructions',
            'delete preconstructions',
            'create resources',
            'view resources',
            'edit resources',
            'delete resources',
            'create safeties',
            'view safeties',
            'edit safeties',
            'delete safeties',
            'create bim models',
            'view bim models',
            'edit bim models',
            'delete bim models',
            'create coordination issues',
            'view coordination issues',
            'edit coordination issues',
            'delete coordination issues',
            'create attic stocks',
            'view attic stocks',
            'edit attic stocks',
            'delete attic stocks',
            'create o&m manuals',
            'view o&m manuals',
            'edit o&m manuals',
            'delete o&m manuals',
            'create warranties',
            'view warranties',
            'edit warranties',
            'delete warranties',
            'create cois',
            'view cois',
            'edit cois',
            'delete cois',
            'create lois',
            'view lois',
            'edit lois',
            'delete lois',
            'create lien waivers',
            'view lien waivers',
            'edit lien waivers',
            'delete lien waivers',
            'create psas',
            'view psas',
            'edit psas',
            'delete psas',
            'create prime contracts',
            'view prime contracts',
            'edit prime contracts',
            'delete prime contracts',
            'create subcontracts',
            'view subcontracts',
            'edit subcontracts',
            'delete subcontracts',
            'create approval directives',
            'view approval directives',
            'edit approval directives',
            'delete approval directives',
            'create budget forecasts',
            'view budget forecasts',
            'edit budget forecasts',
            'delete budget forecasts',
            'create cost change orders',
            'view cost change orders',
            'edit cost change orders',
            'delete cost change orders',
            'create direct costs',
            'view direct costs',
            'edit direct costs',
            'delete direct costs',
            'create invoicings',
            'view invoicings',
            'edit invoicings',
            'delete invoicings',
            'create potential changes',
            'view potential changes',
            'edit potential changes',
            'delete potential changes',
            'create tmm tickets',
            'view tmm tickets',
            'edit tmm tickets',
            'delete tmm tickets',
            'create drawings',
            'view drawings',
            'edit drawings',
            'delete drawings',
            'create file explorers',
            'view file explorers',
            'edit file explorers',
            'delete file explorers',
            'create meeting agenda minutes',
            'view meeting agenda minutes',
            'edit meeting agenda minutes',
            'delete meeting agenda minutes',
            'create permittings',
            'view permittings',
            'edit permittings',
            'delete permittings',
            'create rfis',
            'view rfis',
            'edit rfis',
            'delete rfis',
            'create specifications',
            'view specifications',
            'edit specifications',
            'delete specifications',
            'create submittals',
            'view submittals',
            'edit submittals',
            'delete submittals',
            'create transmittals',
            'view transmittals',
            'edit transmittals',
            'delete transmittals',
            'create checklists',
            'view checklists',
            'edit checklists',
            'delete checklists',
            'create daily reports',
            'view daily reports',
            'edit daily reports',
            'delete daily reports',
            'create photo libraries',
            'view photo libraries',
            'edit photo libraries',
            'delete photo libraries',
            'create field punchlists',
            'view field punchlists',
            'edit field punchlists',
            'delete field punchlists',
            'create schedules',
            'view schedules',
            'edit schedules',
            'delete schedules',
            'create bid manuals',
            'view bid manuals',
            'edit bid manuals',
            'delete bid manuals',
            'create bid packages',
            'view bid packages',
            'edit bid packages',
            'delete bid packages',
            'create qualified bidders',
            'view qualified bidders',
            'edit qualified bidders',
            'delete qualified bidders',
            'create csi divisions',
            'view csi divisions',
            'edit csi divisions',
            'delete csi divisions',
            'create cost codes',
            'view cost codes',
            'edit cost codes',
            'delete cost codes',
            'create equipment rates',
            'view equipment rates',
            'edit equipment rates',
            'delete equipment rates',
            'create labor rates',
            'view labor rates',
            'edit labor rates',
            'delete labor rates',
            'create locations',
            'view locations',
            'edit locations',
            'delete locations',
            'create material rates',
            'view material rates',
            'edit material rates',
            'delete material rates',
            'create employee orientations',
            'view employee orientations',
            'edit employee orientations',
            'delete employee orientations',
            'create jhas',
            'view jhas',
            'edit jhas',
            'delete jhas',
            'create safety observations',
            'view safety observations',
            'edit safety observations',
            'delete safety observations',
            'create ptps',
            'view ptps',
            'edit ptps',
            'delete ptps',

        ];

        foreach ($permissions as $permission) {
            Permission::create(['name' => $permission]);
        }
    }
}